# Generated by Django 4.0 on 2021-12-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombre del autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellido del autor')),
                ('ig', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('fb', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('tw', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('fecha_de_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria Activada/Categoria no Activada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
    ]
