# Generated by Django 4.0 on 2021-12-13 04:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Contenido'),
        ),
    ]
