# Generated by Django 4.0 on 2021-12-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sluh',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
