# Generated by Django 4.0 on 2021-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_rename_sluh_post_slug_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=110, verbose_name='Titulo'),
        ),
    ]
