# Generated by Django 4.0 on 2021-12-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_autor_fecha_de_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_de_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateField(verbose_name='Fecha de creacion'),
        ),
    ]
