# Generated by Django 4.0 on 2021-12-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_autor_fecha_de_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripcion'),
        ),
    ]
