# Generated by Django 4.0 on 2021-12-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_alter_post_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=350, verbose_name='Descripcion'),
        ),
    ]
