# Generated by Django 4.0 on 2021-12-17 21:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog_app', '0014_usuario_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
            ],
            options={
                'ordering': ('first_name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='ig',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='tw',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.post'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
