# Generated by Django 4.0 on 2021-12-17 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_usuarios_alter_comentarios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.usuarios'),
        ),
    ]
