# Generated by Django 4.0 on 2021-12-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_alter_comentarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(blank=True, default='Jeronimo', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.usuarios'),
        ),
    ]
